### ISSUE TITLE
能不能加个 修改时 把之前上传过的图片 直接通过配置文件 然后再渲染出来

### ISSUE THREAD

**Issue by James88** [941477276/UploadPreview#1]
渲染之前已经添加的图片后，使他们和新添加文件一样支持 一些事件 （删除等）...

你的代码帮了我们不少忙 先谢谢了。

**Comment by 941477276** [comment]
你是想实现编辑图片的功能吗？

**Comment by James88** [comment]
是的 现在遇到的问题是 我把图片存起来之后 , 用户再打开页面后 需要让用户还能看到 自己之前传的图片，可以删除之前上传的图片 如果要新增的话 可以继续新增， 我看了下你的js 无奈我的js水平太低不知道如何很轻松借用你的代码..

**Comment by 941477276** [comment]
换一个思路去做吧，之前上传的图片的展示样式与我那个插件的样式一致即可，至于删除你可以自己绑定事件，然后执行相应的操作

**Comment by James88** [comment]
嗯 好的。
